name: mini_pos_checkout
description: A mini POS checkout core implementation
version: 1.0.0
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  equatable: ^2.0.5
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  test: ^1.24.0
  mocktail: ^1.0.3
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/catalog.json